---
title: "Student_2"
output: html_document
---

```{r setup, include=FALSE}
library(grid) 
library(gridExtra)
library(tidyverse)
library(dummies)
library(readxl)
library(knitr)
library(ggplot2)
library(lubridate)
library(arules)
library(arulesViz)
library(plyr)
library(corrplot)
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
deleteRebundantRules <- function (rules) {
  subsetMatrix <- is.subset(rules, rules)
  subsetMatrix[lower.tri(subsetMatrix, diag=TRUE)] <- FALSE
  redundant <- colSums(subsetMatrix, na.rm=TRUE) >= 1
  rules <- rules[!redundant]
  return (rules)
}
```

Vamos a trabajar únicamente con el dataset de la asignatura de portugués
```{r}
studentMat <- read.table("student/student-mat.csv", row.names=NULL, sep=";", header=TRUE)
studentPor <- read.table("student/student-por.csv", row.names=NULL, sep=";", header=TRUE)
```

```{r}
names(studentPor) <- tolower(names(studentPor))
studentPor.factor <- studentPor
studentPor.factor$age <- cut(studentPor$age, breaks = c(14, 18, 22))
studentPor.factor$medu <- as.factor(studentPor$medu)
studentPor.factor$fedu <- as.factor(studentPor$fedu)
studentPor.factor$studytime <- as.factor(studentPor$studytime)
studentPor.factor$traveltime <- as.factor(studentPor$traveltime)
studentPor.factor$failures <- as.factor(studentPor$failures)

studentPor.factor$famrel <- as.factor(studentPor$famrel)
studentPor.factor$freetime <- as.factor(studentPor$freetime)
studentPor.factor$goout <- as.factor(studentPor$goout)
studentPor.factor$walc <- as.factor(studentPor$walc)
studentPor.factor$dalc <- as.factor(studentPor$dalc)
studentPor.factor$health <- as.factor(studentPor$health)
studentPor.factor$absences <- as.factor(studentPor$absences)
studentPor.factor$g1 <- as.factor(ifelse(studentPor$g1 > 9, 1, 0)) #variable a predecir
studentPor.factor$g2 <- as.factor(ifelse(studentPor$g2 > 9, 1, 0)) #variable a predecir
studentPor.factor$g3 <- as.factor(ifelse(studentPor$g3 > 9, 1, 0)) #variable a predecir
```


```{r}
car.transactions <- as(studentPor.factor,"transactions") 
itemFrequencyPlot(car.transactions, support=0.1, cex.names=0.7)
```

A continuación usamos apriori con un soporte mínimo de 0.1 para obtener los itemsets frecuentes.Primera información importante que acceptance=unacc es muy frecuente. En el barplot se muestran los tamaños de itemsets frecuentes. Se ve cómo el tamaño de itemsets más frecuente es 2.

```{r, results='hide'}
car.rules <- apriori(car.transactions, parameter=list(support=0.1,target="frequent"))
inspect(head(car.rules))
barplot(table(size(car.rules)), xlab="itemset size", ylab="count")
```

```{r, results='hide'}
car.rules <- apriori(car.transactions, parameter = list(minlen=7, supp=0.2, conf=0.75))
# car.rules <- deleteRebundantRules(car.rules)
#quality(car.rules) <- cbind(quality(car.rules), interestMeasure(car.rules, c("chiSquare", "conviction", "cosine", "coverage", "leverage", "oddsRatio"), car.dataset))
```
```{r, results='hide'}
car.rules.sorted <- sort(car.rules, by="support")
inspect(head(car.rules.sorted))
plot(car.rules)
```








dd